version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./backend-src
      dockerfile: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/productdb
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

  alembic:
    build:
      context: ./backend-src
      dockerfile: .
    command: alembic upgrade head
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/productdb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend-src
      dockerfile: .
      args:
        - BACKEND_URL="http://127.0.0.1:8000"
    ports:
      - "3000:3000"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge